-- 003: mavzular va sovg'alar (boshlang'ich ma'lumot)
insert into public.fizika_topics(id, title, grades, section, sort) values
('olchash', 'Fizik kattaliklar va o‘lchash', '{6}', 'Mexanika', 0),
('modda', 'Modda tuzilishi. Massa va zichlik', '{6}', 'Molekulyar fizika', 1),
('kinematika', 'Kinematika', '{6,7,10}', 'Mexanika', 2),
('dinamika', 'Dinamika: kuch va Nyuton qonunlari', '{6,7,10}', 'Mexanika', 3),
('saqlanish', 'Impuls, ish va energiya', '{6,7,10}', 'Mexanika', 4),
('statika', 'Statika va oddiy mexanizmlar', '{6,10}', 'Mexanika', 5),
('gidro', 'Bosim, gidro- va aerostatika', '{6,10}', 'Mexanika', 6),
('tebranish', 'Mexanik tebranishlar, to‘lqinlar, tovush', '{6,10}', 'Tebranishlar', 7),
('molekulyar', 'Molekulyar-kinetik nazariya va gaz qonunlari', '{9,10}', 'Molekulyar fizika', 8),
('termodinamika', 'Issiqlik hodisalari va termodinamika', '{6,9,10}', 'Molekulyar fizika', 9),
('suyuq_qattiq', 'Suyuqlik va qattiq jismlar xossalari', '{9}', 'Molekulyar fizika', 10),
('elektrostatika', 'Elektrostatika', '{6,8,10}', 'Elektrodinamika', 11),
('tok', 'O‘zgarmas elektr toki', '{6,8,10}', 'Elektrodinamika', 12),
('muhit_tok', 'Turli muhitlarda elektr toki', '{8,10}', 'Elektrodinamika', 13),
('magnit', 'Magnit maydon', '{8,11}', 'Elektrodinamika', 14),
('induksiya', 'Elektromagnit induksiya', '{11}', 'Elektrodinamika', 15),
('ozgaruvchan_tok', 'EM tebranishlar va o‘zgaruvchan tok', '{11}', 'Tebranishlar', 16),
('optika', 'Geometrik optika', '{6,9}', 'Optika', 17),
('tolqin_optika', 'EM to‘lqinlar va to‘lqin optikasi', '{11}', 'Optika', 18),
('nisbiylik', 'Nisbiylik nazariyasi', '{11}', 'Zamonaviy fizika', 19),
('kvant', 'Kvant fizikasi', '{11}', 'Zamonaviy fizika', 20),
('yadro', 'Atom va yadro fizikasi', '{11}', 'Zamonaviy fizika', 21)
on conflict (id) do update set title = excluded.title, grades = excluded.grades, section = excluded.section, sort = excluded.sort;

insert into public.fizika_rewards(id, title, description, icon, kind, cost_coins, audience, rule, sort) values
('first_test', 'Birinchi qadam', 'Birinchi testni yakunladingiz', '👣', 'badge', 0, 'all', '{"tests":1}'::jsonb, 1),
('tests_10', 'Sinovchi', '10 ta test yakunlandi', '🧪', 'badge', 0, 'all', '{"tests":10}'::jsonb, 2),
('tests_50', 'Test ustasi', '50 ta test yakunlandi', '🎓', 'badge', 0, 'all', '{"tests":50}'::jsonb, 3),
('perfect_1', 'Xatosiz', 'Kamida 5 savolli testda hammasi to‘g‘ri', '🎯', 'badge', 0, 'all', '{"perfect":1}'::jsonb, 4),
('perfect_5', 'Beshlik', '5 marta xatosiz natija', '5️⃣', 'badge', 0, 'all', '{"perfect":5}'::jsonb, 5),
('streak_3', 'Uch kun ketma-ket', '3 kun uzluksiz shug‘ullanish', '🔥', 'badge', 0, 'all', '{"streak":3}'::jsonb, 6),
('streak_7', 'Haftalik olov', '7 kun uzluksiz', '☄️', 'badge', 0, 'all', '{"streak":7}'::jsonb, 7),
('streak_30', 'Oy chempioni', '30 kun uzluksiz', '🌙', 'badge', 0, 'all', '{"streak":30}'::jsonb, 8),
('xp_500', 'Zaryadlangan', '500 XP to‘plandi', '⚡', 'badge', 0, 'all', '{"xp":500}'::jsonb, 9),
('xp_2000', 'Yadro energiyasi', '2000 XP to‘plandi', '☢️', 'badge', 0, 'all', '{"xp":2000}'::jsonb, 10),
('xp_5000', 'Yulduz', '5000 XP to‘plandi', '⭐', 'badge', 0, 'all', '{"xp":5000}'::jsonb, 11),
('games_5', 'Tajribachi', '5 ta laboratoriya o‘yini', '🔬', 'badge', 0, 'all', '{"games":5}'::jsonb, 12),
('games_25', 'Laboratoriya sohibi', '25 ta o‘yin', '🧲', 'badge', 0, 'all', '{"games":25}'::jsonb, 13),
('daily_7', 'Kunlik intizom', '7 ta kunlik test', '📅', 'badge', 0, 'all', '{"daily":7}'::jsonb, 14),
('milliy_1', 'Imtihon sinovi', 'Milliy sertifikat sinovini to‘liq yechdingiz', '📜', 'badge', 0, 'all', '{"milliy":1}'::jsonb, 15),
('av_magnet', 'Magnit avatar', 'Profil uchun 🧲', '🧲', 'avatar', 50, 'all', '{}'::jsonb, 30),
('av_flask', 'Kolba avatar', 'Profil uchun 🧪', '🧪', 'avatar', 60, 'all', '{}'::jsonb, 31),
('av_scope', 'Teleskop avatar', 'Profil uchun 🔭', '🔭', 'avatar', 80, 'all', '{}'::jsonb, 32),
('av_bolt', 'Chaqmoq avatar', 'Profil uchun ⚡', '⚡', 'avatar', 100, 'all', '{}'::jsonb, 33),
('av_planet', 'Sayyora avatar', 'Profil uchun 🪐', '🪐', 'avatar', 150, 'all', '{}'::jsonb, 34),
('av_rocket', 'Raketa avatar', 'Profil uchun 🚀', '🚀', 'avatar', 250, 'all', '{}'::jsonb, 35),
('ti_newton', 'Yosh Nyuton', 'Reytingda ko‘rinadigan unvon', '🍎', 'title', 120, 'student', '{}'::jsonb, 40),
('ti_student', 'Kelajak talabasi', 'Reytingda ko‘rinadigan unvon', '🏛️', 'title', 120, 'abiturient', '{}'::jsonb, 41),
('ti_lab', 'Laboratoriya boshlig‘i', 'Noyob unvon', '🥼', 'title', 300, 'all', '{}'::jsonb, 42),
('gift_cert', 'Faxriy yorliq', 'Ismingiz yozilgan chop etiladigan yorliq', '🏆', 'gift', 500, 'all', '{}'::jsonb, 50)
on conflict (id) do update set title = excluded.title, description = excluded.description, icon = excluded.icon, kind = excluded.kind, cost_coins = excluded.cost_coins, audience = excluded.audience, rule = excluded.rule, sort = excluded.sort;
