#!/usr/bin/env node
// Builds the seed migration and the app's offline content bundle from /content.
// IDs are deterministic (md5 of a stable key) so the app's bundled lessons and the
// database rows share the same UUIDs and offline progress syncs to the right lesson.
//
//   node scripts/build-content.mjs          # write files
//   node scripts/build-content.mjs --check  # fail if generated files are stale (CI)
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const LANGS = ['uz', 'ru', 'en'];
const read = (f) => JSON.parse(readFileSync(join(root, 'content', f), 'utf8'));

export const stableId = (key) => {
  const h = createHash('md5').update(`elektruy:${key}`).digest('hex');
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20)}`;
};
const q = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replaceAll("'", "''")}'`);
const j = (v) => `${q(JSON.stringify(v))}::jsonb`;

const lessons = read('lessons.json');
const materials = read('materials.json');
const config = read('config.json');
const legal = read('legal.json');

// ----------------------------------------------------------------- validation
const errors = [];
const need = (cond, msg) => { if (!cond) errors.push(msg); };
for (const l of lessons.lessons) {
  for (const lang of LANGS) need(l.t[lang]?.title, `${l.slug}: missing ${lang} title`);
  l.steps.forEach((s, i) => LANGS.forEach((lang) => need(s.t[lang]?.text, `${l.slug} step ${i + 1}: missing ${lang}`)));
  l.quiz.forEach((qq, i) => LANGS.forEach((lang) => {
    need(qq.t[lang]?.q, `${l.slug} quiz ${i + 1}: missing ${lang}`);
    need(qq.t[lang]?.options?.length > qq.correct, `${l.slug} quiz ${i + 1}: bad options ${lang}`);
  }));
  for (const s of l.steps) for (const tool of s.tools) {
    need(materials.materials.some((m) => m.key === tool), `${l.slug}: unknown tool ${tool}`);
  }
}
for (const m of materials.materials) LANGS.forEach((lang) => need(m.t[lang], `material ${m.key}: missing ${lang}`));
for (const t of legal.texts) LANGS.forEach((lang) => need(t.t[lang], `legal ${t.kind}: missing ${lang}`));
if (errors.length) {
  console.error(errors.join('\n'));
  process.exit(1);
}

// ----------------------------------------------------------------- bundle (app)
const bundleLessons = lessons.lessons.map((l) => ({
  id: stableId(`lesson:${l.slug}`),
  slug: l.slug,
  sort_order: l.order,
  difficulty: l.difficulty,
  est_minutes: l.est_minutes,
  icon: l.icon,
  t: l.t,
  steps: l.steps.map((s, i) => ({
    id: stableId(`step:${l.slug}:${i}`),
    sort_order: i,
    illustration: s.illustration,
    image_path: null,
    tools: s.tools,
    t: s.t,
  })),
  quiz: l.quiz.map((qq, i) => ({ id: stableId(`quiz:${l.slug}:${i}`), sort_order: i, correct_index: qq.correct, t: qq.t })),
}));
const bundleMaterials = materials.materials.map((m, i) => ({
  id: stableId(`material:${m.key}`), key: m.key, category: m.category, unit: m.unit,
  default_price: m.price, currency: materials.currency, sort_order: i, t: m.t,
}));

const outputs = new Map();
const appContent = join(root, 'app', 'assets', 'content');
outputs.set(join(appContent, 'lessons.json'), JSON.stringify({ version: lessons.version, lessons: bundleLessons }, null, 1));
outputs.set(join(appContent, 'materials.json'), JSON.stringify({ version: materials.version, materials: bundleMaterials, regions: materials.regions }, null, 1));
const { _note, version: _v, ...configRows } = config;
outputs.set(join(appContent, 'config.json'), JSON.stringify(configRows, null, 1));
outputs.set(join(appContent, 'legal.json'), JSON.stringify(legal, null, 1));

// ----------------------------------------------------------------- seed SQL
const sql = [];
sql.push('-- GENERATED by scripts/build-content.mjs from /content — do not edit by hand.');
sql.push('-- Idempotent: re-running never overwrites rows an admin has edited.');
sql.push('');
sql.push('insert into public.ew_regions (code, name_uz, name_ru, name_en, sort_order) values');
sql.push(materials.regions.map((r, i) => `  (${q(r.code)}, ${q(r.t.uz)}, ${q(r.t.ru)}, ${q(r.t.en)}, ${i})`).join(',\n') + '\non conflict (code) do nothing;\n');

sql.push('insert into public.ew_materials (id, key, category, unit, default_price, currency, sort_order) values');
sql.push(bundleMaterials.map((m) => `  (${q(m.id)}, ${q(m.key)}, ${q(m.category)}, ${q(m.unit)}, ${m.default_price}, ${q(m.currency)}, ${m.sort_order})`).join(',\n') + '\non conflict (key) do nothing;\n');
sql.push('insert into public.ew_material_translations (material_id, lang, name) values');
sql.push(bundleMaterials.flatMap((m) => LANGS.map((lang) => `  (${q(m.id)}, ${q(lang)}, ${q(m.t[lang])})`)).join(',\n') + '\non conflict do nothing;\n');

// Lessons are seeded from one jsonb literal (smaller than row-per-insert SQL).
const lessonJson = JSON.stringify(bundleLessons);
if (lessonJson.includes('$ew$')) throw new Error('lesson content contains $ew$');
sql.push(`select ew_private.seed_lessons($ew$${lessonJson}$ew$::jsonb);\n`);

sql.push('insert into public.ew_app_config (key, value) values');
sql.push(Object.entries(configRows).map(([k, v]) => `  (${q(k)}, ${j(v)})`).join(',\n') + '\non conflict (key) do nothing;\n');

sql.push('insert into public.ew_legal_texts (kind, version, lang, body, published) values');
sql.push(legal.texts.flatMap((t) => LANGS.map((lang) => `  (${q(t.kind)}, ${t.version}, ${q(lang)}, ${q(t.t[lang])}, true)`)).join(',\n') + '\non conflict (kind, version, lang) do nothing;\n');

outputs.set(join(root, 'supabase', 'migrations', '20261006120400_ew_seed.sql'), sql.join('\n'));

// ----------------------------------------------------------------- write / check
const check = process.argv.includes('--check');
let stale = 0;
for (const [file, content] of outputs) {
  const body = content.endsWith('\n') ? content : content + '\n';
  if (check) {
    if (!existsSync(file) || readFileSync(file, 'utf8') !== body) {
      console.error(`stale: ${file}`);
      stale++;
    }
  } else {
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, body);
    console.log(`wrote ${file.replace(root + '/', '')}`);
  }
}
if (stale) process.exit(1);
