/* Tarjimalar (uz/ru/en). index.html da o‘zbekcha matn bor; bu fayl tilni almashtirish uchun. */
window.MU_I18N = {
 "uz": {
  "nav.about": "Men haqimda",
  "nav.tools": "Vositalar",
  "nav.skills": "Yo‘nalishlar",
  "nav.projects": "Loyihalar",
  "nav.app": "Rele Lug‘at",
  "nav.food": "Uy taomlari",
  "nav.pets": "Mushuk va Itlar",
  "nav.contact": "Aloqa",
  "skip": "Asosiy mazmunga o‘tish",
  "meta.title": "Mushuk va Itlarni Top: Android ilovasini yuklab olish va foydalanish qo‘llanmasi | EnergyVibe",
  "meta.desc": "Ko‘chada uchragan mushuk va itlarni suratga oling, GPS joylashuvi avtomatik belgilanadi. Android ilovasini (APK) yuklab oling, o‘rnatish va foydalanish bo‘yicha qadamma-qadam qo‘llanma. O‘zbek, rus va ingliz tillari, qorong‘u rejim.",
  "h.eyebrow": "Android · bepul · APK",
  "h.title": "Mushuk va Itlarni <span class=\"mu-grad\">Top</span>",
  "h.lead": "Ko‘chada mushuk yoki it uchradimi? Suratga oling: joylashuv avtomatik belgilanadi. Yo‘qolgan yoki topilgan hayvonni yaqin atrofdagi e’lonlardan va xaritadan toping.",
  "h.cta": "Ilovani yuklab olish",
  "h.guide": "Foydalanish qo‘llanmasi ↓",
  "h.ios": "⚠️ Ilova hozircha faqat <b>Android</b> uchun. iPhone uchun versiya yo‘q.",
  "h.iconName": "Mushuk va Itlarni Top",
  "h.iconSub": "Google · GPS · xarita",
  "h.f1": "🐱 mushuk",
  "h.f2": "🐶 it",
  "h.f3": "📍 lokatsiya",
  "d.station": "Yuklab olish",
  "d.title": "APK faylni yuklab oling",
  "d.lead": "Ilova Google Play’da emas, shuning uchun to‘g‘ridan-to‘g‘ri APK fayl sifatida beriladi. Bepul va reklamasiz.",
  "d.name": "Mushuk va Itlarni Top",
  "d.desc": "Ko‘rdingmi: belgila. Qidiryapsanmi: top! Rasmga oling, joylashuv avtomatik saqlanadi, boshqalar uni xaritada ko‘radi.",
  "d.f1": "Google orqali kirish",
  "d.f2": "Kamera va avtomatik GPS",
  "d.f3": "Yaqin atrofdagi e’lonlar va xarita",
  "d.f4": "Layk, izoh, bildirishnomalar",
  "d.f5": "3 til · qorong‘u rejim",
  "d.btn": "Yuklab olish (APK)",
  "d.android": "Android 5.1+",
  "d.fine": "Fayl butunligini SHA-256 bilan tekshirish mumkin (ixtiyoriy). Barcha versiyalar:",
  "i.station": "O‘rnatish",
  "i.title": "Telefoningizga o‘rnatish: 5 qadam",
  "i1.t": "APK faylni yuklab oling",
  "i1.p": "Yuqoridagi tugmani bosing. Fayl telefonning <b>Yuklamalar</b> (Downloads) papkasiga tushadi. Telegram yoki Instagram ichidagi brauzerda yuklash ishlamasa, havolani <b>Chrome</b>’da oching.",
  "i2.t": "Faylni oching",
  "i2.p": "Brauzer pastida «Ochish» chiqadi yoki <b>Fayllar → Yuklamalar</b> orqali <code>mushuk-it-top.apk</code> ni bosing.",
  "i3.t": "Noma’lum manbalarga ruxsat bering",
  "i3.p": "Android so‘rasa: <b>Sozlamalar</b>ni bosing va <b>«Ushbu manbadan o‘rnatishga ruxsat»</b> ni yoqing (Chrome yoki Fayllar uchun). Keyin orqaga qaytib o‘rnatishni davom ettiring. Bu ruxsatni keyin o‘chirib qo‘yish mumkin.",
  "i4.t": "Play Protect ogohlantirishi",
  "i4.p": "«Zararli bo‘lishi mumkin» degan oyna chiqsa: ilova Play Store’da emasligi uchun shunday bo‘ladi. <b>«Batafsil»</b> → <b>«Baribir o‘rnatish»</b> ni bosing.",
  "i5.t": "Oching va Google bilan kiring",
  "i5.p": "Ilovani oching, <b>«Google bilan kirish»</b> ni bosing, so‘ng ism-sharifingizni kiriting. Kamera va joylashuv ruxsati so‘ralganda <b>«Ilovadan foydalanayotganda»</b> ni tanlang.",
  "g.station": "Qo‘llanma",
  "g.title": "Foydalanish qo‘llanmasi",
  "g.lead": "Ilovada 6 ta asosiy amal bor. Har bir qadam ekran rasmi bilan ko‘rsatilgan.",
  "g1.t": "Kirish va profil",
  "g1.p": "Ilovani oching va <b>«Google bilan kirish»</b> ni bosing. Birinchi kirishda ism-sharifingizni kiriting (telefon va shahar ixtiyoriy): boshqa foydalanuvchilar sizni shu ism bilan ko‘radi. Kirish ekranida pastdagi tugmalar orqali tilni almashtirish mumkin.",
  "g2.t": "Yaqin atrofdagi e’lonlar",
  "g2.p": "Bosh sahifada sizga eng yaqin e’lonlar masofa bilan ko‘rinadi (masalan, «620 m»). <b>Mushuk</b> yoki <b>It</b> plitkasi turini tanlaydi, qidiruv sarlavha, izoh yoki manzil bo‘yicha topadi, <b>«Barchasi»</b> to‘liq lentani ochadi.",
  "g3.t": "Xarita",
  "g3.p": "Pastdagi <b>Xarita</b> tabida e’lonlar rasmli pinlar bilan ko‘rinadi (mushuk to‘q sariq, it ko‘k). Filtr va qidiruvdan foydalaning, pinni bosing: pastda e’lon kartasi chiqadi, <b>«Lokatsiyani ko‘rish»</b> tafsilotlarni ochadi. Ko‘k nuqta siz turgan joy, yuqori o‘ngdagi tugma xaritani sizga qaytaradi.",
  "g4.t": "E’lon qo‘yish",
  "g4.p": "Pastdagi yashil <b>«+»</b> tugmasini bosing va <b>Mushuk</b> yoki <b>It</b>ni tanlang: kamera ochiladi. Rasmga olgan zahoti <b>GPS joylashuv avtomatik</b> olinadi va manzil yoziladi. Sarlavha (masalan, «Oq mushuk») va izoh qo‘shib, <b>«E’lon qilish»</b> ni bosing. Joylashuv olinmasa e’lon yuborilmaydi: GPS yoqilganini tekshirib, tugma bilan qayta urinib ko‘ring.",
  "g5.t": "Tafsilotlar, layk va izoh",
  "g5.p": "Istalgan e’longa bosing: joylashuv, masofa va mini xarita ko‘rinadi. <b>«Google Maps’da ochish»</b> yo‘nalish olishga yordam beradi. <b>Layk</b> bosing va pastdagi maydonda <b>izoh</b> yozing. O‘z e’loningizni yuqori o‘ngdagi axlat qutisi belgisi bilan o‘chirasiz.",
  "g6.t": "Bildirishnomalar va profil",
  "g6.p": "Kimdir e’loningizga layk bosganda yoki izoh yozganda <b>Xabarlar</b> tabida qizil raqam chiqadi. <b>Profil</b>da statistikangiz, mening e’lonlarim, sevimlilarim va izohlarim; <b>Sozlamalar</b>da <b>til</b> (o‘zbekcha, русский, English) va <b>qorong‘u rejim</b> tanlanadi.",
  "g.dark": "Qorong‘u rejim",
  "t.station": "Muhim",
  "t.title": "Ruxsatlar va qoidalar",
  "t1.t": "📷 Kamera",
  "t1.p": "Rasmga olish uchun kerak. Ruxsatni rad etgan bo‘lsangiz: <b>Sozlamalar → Ilovalar → Mushuk va Itlarni Top → Ruxsatlar</b>.",
  "t2.t": "📍 Joylashuv",
  "t2.p": "Rasm olingan joyni belgilash va yaqin e’lonlarni ko‘rsatish uchun. <b>«Ilovadan foydalanayotganda»</b> yetarli: ilova fonda joylashuv olmaydi. Ruxsatsiz e’lon qo‘yib bo‘lmaydi.",
  "t3.t": "🛡️ Qoidalar",
  "t3.p": "Faqat hayvonga tegishli o‘zingiz olgan rasmni joylang. Spam va haqoratli izohlarni administrator o‘chiradi, qoidabuzarni bloklaydi. Telefon raqamingiz va emailingiz boshqalarga ko‘rinmaydi.",
  "f.station": "Muammolar",
  "f.title": "Ko‘p beriladigan savollar",
  "q1.q": "«Ilova o‘rnatilmadi» yoki «Paket buzilgan» deyapti",
  "q1.a": "Faylni qayta yuklab oling (yuklash uzilgan bo‘lishi mumkin) va hajmi yuqoridagi bilan bir xil ekanini tekshiring. Boshqa usulda o‘rnatilgan shu nomli eski versiya bo‘lsa, uni o‘chirib qaytadan o‘rnating. Telefonda bo‘sh joy ham kerak.",
  "q2.q": "Fayl yuklanmayapti",
  "q2.a": "Telegram/Instagram ichidagi brauzer o‘rniga Chrome’da oching. Internet barqaror bo‘lsin. Havolani uzoq bosib «Yuklab olish»ni tanlash ham yordam beradi.",
  "q3.q": "Google bilan kira olmayapman",
  "q3.a": "Internet borligini va brauzer (Chrome) yangilanganini tekshiring. Kirgach ilovaga avtomatik qaytilmasa, ilovani yoping va qayta oching. «Access blocked» chiqsa, administratorga murojaat qiling.",
  "q4.q": "Joylashuv aniqlanmayapti",
  "q4.a": "Telefonda GPS (Joylashuv) yoqilgan va ilovaga ruxsat berilgan bo‘lishi kerak. Ochiq joyda qayta urinib ko‘ring. Quvvat tejash rejimi aniqlikni pasaytirishi mumkin.",
  "q5.q": "E’lonim boshqalarga ko‘rinmayapti",
  "q5.a": "Administrator e’lonni bloklagan bo‘lishi mumkin: bunda e’lon ostida qizil ogohlantirish chiqadi va u faqat sizga ko‘rinadi. Aniqlik uchun administratorga yozing.",
  "q6.q": "Tilni yoki qorong‘u rejimni qanday o‘zgartiraman?",
  "q6.a": "Profil → Sozlamalar. Til: o‘zbekcha, русский, English. Mavzu: Tizim (telefon sozlamasiga ergashadi), Yorug‘ yoki Qorong‘u.",
  "q7.q": "iPhone uchun ilova bormi?",
  "q7.a": "Hozircha yo‘q: ilova faqat Android uchun.",
  "q8.q": "Ilova xavfsizmi?",
  "q8.a": "Ilova faqat kamera va joylashuv ruxsatini so‘raydi. Ma’lumotlar himoyalangan serverda saqlanadi; boshqalar faqat ismingiz va e’loningizni ko‘radi, email va telefon ko‘rinmaydi.",
  "foot.home": "Bosh sahifa",
  "foot.right": ""
 },
 "ru": {
  "nav.about": "Обо мне",
  "nav.tools": "Инструменты",
  "nav.skills": "Направления",
  "nav.projects": "Проекты",
  "nav.app": "Rele Lug‘at",
  "nav.food": "Домашняя еда",
  "nav.pets": "Кошки и собаки",
  "nav.contact": "Контакты",
  "skip": "Перейти к основному содержимому",
  "meta.title": "Найди кошек и собак: скачать Android-приложение и инструкция | EnergyVibe",
  "meta.desc": "Фотографируйте кошек и собак, которых встретили, и GPS-метка ставится автоматически. Скачайте Android-приложение (APK), пошаговая инструкция по установке и использованию. Узбекский, русский и английский языки, тёмная тема.",
  "h.eyebrow": "Android · бесплатно · APK",
  "h.title": "Найди кошек <span class=\"mu-grad\">и собак</span>",
  "h.lead": "Встретили кошку или собаку на улице? Сфотографируйте: место отметится автоматически. Находите потерявшихся и найденных животных среди объявлений рядом и на карте.",
  "h.cta": "Скачать приложение",
  "h.guide": "Инструкция по использованию ↓",
  "h.ios": "⚠️ Приложение пока только для <b>Android</b>. Версии для iPhone нет.",
  "h.iconName": "Найди кошек и собак",
  "h.iconSub": "Google · GPS · карта",
  "h.f1": "🐱 кошка",
  "h.f2": "🐶 собака",
  "h.f3": "📍 место",
  "d.station": "Скачать",
  "d.title": "Скачайте APK-файл",
  "d.lead": "Приложения нет в Google Play, поэтому оно распространяется напрямую в виде APK-файла. Бесплатно и без рекламы.",
  "d.name": "Найди кошек и собак",
  "d.desc": "Увидел: отметь. Ищешь: найди! Сфотографируйте, место сохранится автоматически, а другие увидят его на карте.",
  "d.f1": "Вход через Google",
  "d.f2": "Камера и автоматический GPS",
  "d.f3": "Объявления рядом и карта",
  "d.f4": "Лайки, комментарии, уведомления",
  "d.f5": "3 языка · тёмная тема",
  "d.btn": "Скачать (APK)",
  "d.android": "Android 5.1+",
  "d.fine": "Целостность файла можно проверить по SHA-256 (необязательно). Все версии:",
  "i.station": "Установка",
  "i.title": "Установка на телефон: 5 шагов",
  "i1.t": "Скачайте APK-файл",
  "i1.p": "Нажмите кнопку выше. Файл попадёт в папку <b>Загрузки</b> (Downloads). Если загрузка не работает во встроенном браузере Telegram или Instagram, откройте ссылку в <b>Chrome</b>.",
  "i2.t": "Откройте файл",
  "i2.p": "Внизу браузера появится «Открыть», или нажмите <code>mushuk-it-top.apk</code> через <b>Файлы → Загрузки</b>.",
  "i3.t": "Разрешите установку из неизвестных источников",
  "i3.p": "Если Android спросит: нажмите <b>Настройки</b> и включите <b>«Разрешить установку из этого источника»</b> (для Chrome или Файлов). Затем вернитесь назад и продолжите установку. Позже это разрешение можно отключить.",
  "i4.t": "Предупреждение Play Protect",
  "i4.p": "Если появится окно «Приложение может быть опасным»: так бывает, потому что его нет в Play Маркете. Нажмите <b>«Подробнее»</b> → <b>«Всё равно установить»</b>.",
  "i5.t": "Откройте и войдите через Google",
  "i5.p": "Откройте приложение, нажмите <b>«Войти через Google»</b> и введите имя и фамилию. Когда спросят разрешение на камеру и местоположение, выберите <b>«Только при использовании приложения»</b>.",
  "g.station": "Инструкция",
  "g.title": "Руководство пользователя",
  "g.lead": "В приложении 6 основных действий. Каждый шаг показан на скриншоте.",
  "g1.t": "Вход и профиль",
  "g1.p": "Откройте приложение и нажмите <b>«Войти через Google»</b>. При первом входе введите имя и фамилию (телефон и город по желанию): другие пользователи увидят вас под этим именем. Язык можно сменить кнопками внизу экрана входа.",
  "g2.t": "Объявления рядом",
  "g2.p": "На главной вы увидите ближайшие к вам объявления с расстоянием (например, «620 м»). Плитки <b>Кошка</b> и <b>Собака</b> выбирают вид, поиск находит по заголовку, описанию или адресу, а <b>«Все»</b> открывает полную ленту.",
  "g3.t": "Карта",
  "g3.p": "На вкладке <b>Карта</b> объявления показаны фото-метками (кошки оранжевые, собаки синие). Пользуйтесь фильтром и поиском, нажмите метку: внизу появится карточка, а <b>«Показать место»</b> откроет подробности. Синяя точка это вы, кнопка справа вверху возвращает карту к вам.",
  "g4.t": "Как опубликовать объявление",
  "g4.p": "Нажмите зелёную кнопку <b>«+»</b> внизу и выберите <b>Кошка</b> или <b>Собака</b>: откроется камера. Сразу после снимка <b>GPS-местоположение определяется автоматически</b>, а адрес подставляется сам. Добавьте заголовок (например, «Белая кошка») и описание и нажмите <b>«Опубликовать»</b>. Без местоположения объявление не отправляется: проверьте GPS и повторите кнопкой.",
  "g5.t": "Подробности, лайки и комментарии",
  "g5.p": "Нажмите на любое объявление: увидите местоположение, расстояние и мини-карту. <b>«Открыть в Google Maps»</b> поможет построить маршрут. Поставьте <b>лайк</b> и напишите <b>комментарий</b> в поле внизу. Своё объявление можно удалить значком корзины справа вверху.",
  "g6.t": "Уведомления и профиль",
  "g6.p": "Когда кто-то ставит лайк или комментирует ваше объявление, на вкладке <b>Уведомл.</b> появляется красный счётчик. В <b>Профиле</b> ваша статистика, мои объявления, избранное и комментарии; в <b>Настройках</b> выбираются <b>язык</b> (o‘zbekcha, русский, English) и <b>тёмная тема</b>.",
  "g.dark": "Тёмная тема",
  "t.station": "Важно",
  "t.title": "Разрешения и правила",
  "t1.t": "📷 Камера",
  "t1.p": "Нужна для съёмки. Если вы отказали в разрешении: <b>Настройки → Приложения → Найди кошек и собак → Разрешения</b>.",
  "t2.t": "📍 Местоположение",
  "t2.p": "Чтобы отметить место снимка и показать объявления рядом. Достаточно <b>«Только при использовании»</b>: приложение не следит в фоне. Без разрешения объявление не опубликовать.",
  "t3.t": "🛡️ Правила",
  "t3.p": "Публикуйте только свои фото животных. Спам и оскорбительные комментарии удаляет администратор, нарушителей блокирует. Ваш телефон и email другим не видны.",
  "f.station": "Проблемы",
  "f.title": "Частые вопросы",
  "q1.q": "«Приложение не установлено» или «Пакет повреждён»",
  "q1.a": "Скачайте файл заново (загрузка могла прерваться) и проверьте, что размер совпадает с указанным выше. Если установлена старая версия, установленная другим способом, удалите её и поставьте заново. Нужно и свободное место на телефоне.",
  "q2.q": "Файл не скачивается",
  "q2.a": "Откройте ссылку в Chrome вместо встроенного браузера Telegram/Instagram. Нужен стабильный интернет. Поможет и долгое нажатие на ссылку с выбором «Скачать».",
  "q3.q": "Не получается войти через Google",
  "q3.a": "Проверьте интернет и что браузер (Chrome) обновлён. Если после входа приложение не открылось само, закройте и откройте его снова. Если появилось «Access blocked», обратитесь к администратору.",
  "q4.q": "Местоположение не определяется",
  "q4.a": "На телефоне должен быть включён GPS (Геолокация), а у приложения есть разрешение. Попробуйте ещё раз на открытом месте. Режим энергосбережения может снижать точность.",
  "q5.q": "Моё объявление не видно другим",
  "q5.a": "Возможно, администратор заблокировал объявление: под ним появится красное предупреждение, и видно оно только вам. Напишите администратору, чтобы уточнить.",
  "q6.q": "Как сменить язык или тёмную тему?",
  "q6.a": "Профиль → Настройки. Язык: o‘zbekcha, русский, English. Тема: Системная (как в телефоне), Светлая или Тёмная.",
  "q7.q": "Есть ли приложение для iPhone?",
  "q7.a": "Пока нет: приложение только для Android.",
  "q8.q": "Приложение безопасно?",
  "q8.a": "Приложение запрашивает только доступ к камере и местоположению. Данные хранятся на защищённом сервере; другие видят лишь ваше имя и объявления, email и телефон скрыты.",
  "foot.home": "Главная",
  "foot.right": ""
 },
 "en": {
  "nav.about": "About",
  "nav.tools": "Tools",
  "nav.skills": "Expertise",
  "nav.projects": "Projects",
  "nav.app": "Rele Lug‘at",
  "nav.food": "Home Food",
  "nav.pets": "Cats & Dogs",
  "nav.contact": "Contact",
  "skip": "Skip to main content",
  "meta.title": "Find Cats & Dogs: download the Android app and user guide | EnergyVibe",
  "meta.desc": "Photograph cats and dogs you meet and the GPS location is saved automatically. Download the Android app (APK) with step-by-step install and user guide. Uzbek, Russian and English, dark mode.",
  "h.eyebrow": "Android · free · APK",
  "h.title": "Find <span class=\"mu-grad\">Cats &amp; Dogs</span>",
  "h.lead": "Spotted a cat or a dog on the street? Snap a photo and the location is marked automatically. Find lost and found animals in nearby posts and on the map.",
  "h.cta": "Download the app",
  "h.guide": "User guide ↓",
  "h.ios": "⚠️ The app is for <b>Android</b> only for now. There is no iPhone version.",
  "h.iconName": "Find Cats & Dogs",
  "h.iconSub": "Google · GPS · map",
  "h.f1": "🐱 cat",
  "h.f2": "🐶 dog",
  "h.f3": "📍 location",
  "d.station": "Download",
  "d.title": "Download the APK",
  "d.lead": "The app is not on Google Play, so it is distributed directly as an APK file. Free and ad-free.",
  "d.name": "Find Cats & Dogs",
  "d.desc": "Spotted one? Mark it. Looking for one? Find it! Take a photo, the location is saved automatically, and others see it on the map.",
  "d.f1": "Sign in with Google",
  "d.f2": "Camera and automatic GPS",
  "d.f3": "Nearby posts and map",
  "d.f4": "Likes, comments, notifications",
  "d.f5": "3 languages · dark mode",
  "d.btn": "Download (APK)",
  "d.android": "Android 5.1+",
  "d.fine": "You can verify the file with SHA-256 (optional). All versions:",
  "i.station": "Install",
  "i.title": "Installing on your phone: 5 steps",
  "i1.t": "Download the APK file",
  "i1.p": "Tap the button above. The file lands in your phone’s <b>Downloads</b> folder. If downloading does not work in the in-app browser of Telegram or Instagram, open the link in <b>Chrome</b>.",
  "i2.t": "Open the file",
  "i2.p": "Tap “Open” at the bottom of the browser, or tap <code>mushuk-it-top.apk</code> in <b>Files → Downloads</b>.",
  "i3.t": "Allow unknown sources",
  "i3.p": "If Android asks: tap <b>Settings</b> and turn on <b>“Allow from this source”</b> (for Chrome or Files). Then go back and continue installing. You can turn this permission off afterwards.",
  "i4.t": "Play Protect warning",
  "i4.p": "If a “might be harmful” dialog appears, that is only because the app is not on the Play Store. Tap <b>“More details”</b> → <b>“Install anyway”</b>.",
  "i5.t": "Open it and sign in with Google",
  "i5.p": "Open the app, tap <b>“Sign in with Google”</b> and enter your full name. When asked for camera and location access, choose <b>“While using the app”</b>.",
  "g.station": "Guide",
  "g.title": "User guide",
  "g.lead": "The app has 6 main actions. Each step is shown with a screenshot.",
  "g1.t": "Sign in and profile",
  "g1.p": "Open the app and tap <b>“Sign in with Google”</b>. On first sign-in enter your full name (phone and city are optional): other users will see you under this name. You can change the language with the buttons at the bottom of the sign-in screen.",
  "g2.t": "Posts near you",
  "g2.p": "The home screen shows the posts closest to you with the distance (for example “620 m”). The <b>Cat</b> and <b>Dog</b> tiles pick the kind, search finds by title, note or address, and <b>“All”</b> opens the full feed.",
  "g3.t": "Map",
  "g3.p": "On the <b>Map</b> tab posts appear as photo pins (cats orange, dogs blue). Use the filter and search, tap a pin: a card appears at the bottom and <b>“View location”</b> opens the details. The blue dot is you, and the button at the top right brings the map back to you.",
  "g4.t": "Posting",
  "g4.p": "Tap the green <b>“+”</b> button at the bottom and choose <b>Cat</b> or <b>Dog</b>: the camera opens. Right after the shot the <b>GPS location is captured automatically</b> and the address is filled in. Add a title (for example “White cat”) and a note, then tap <b>“Publish”</b>. Without a location the post cannot be sent: check that GPS is on and retry with the button.",
  "g5.t": "Details, likes and comments",
  "g5.p": "Tap any post to see the location, distance and a mini map. <b>“Open in Google Maps”</b> helps you get directions. Give it a <b>like</b> and write a <b>comment</b> in the field at the bottom. Delete your own post with the trash icon at the top right.",
  "g6.t": "Notifications and profile",
  "g6.p": "When someone likes or comments on your post, a red counter appears on the <b>Alerts</b> tab. <b>Profile</b> holds your stats, my posts, favorites and my comments; <b>Settings</b> lets you pick the <b>language</b> (o‘zbekcha, русский, English) and <b>dark mode</b>.",
  "g.dark": "Dark mode",
  "t.station": "Good to know",
  "t.title": "Permissions and rules",
  "t1.t": "📷 Camera",
  "t1.p": "Needed to take photos. If you denied it: <b>Settings → Apps → Find Cats & Dogs → Permissions</b>.",
  "t2.t": "📍 Location",
  "t2.p": "To mark where the photo was taken and to show nearby posts. <b>“While using the app”</b> is enough: the app does not track you in the background. Without it you cannot post.",
  "t3.t": "🛡️ Rules",
  "t3.p": "Post only your own photos of animals. An administrator removes spam and abusive comments and blocks offenders. Your phone number and email are not visible to others.",
  "f.station": "Troubleshooting",
  "f.title": "Frequently asked questions",
  "q1.q": "“App not installed” or “Package is corrupt”",
  "q1.a": "Download the file again (the download may have been interrupted) and check that the size matches the one above. If an older copy installed another way exists, uninstall it and install again. You also need free storage.",
  "q2.q": "The file will not download",
  "q2.a": "Open the link in Chrome instead of the in-app browser of Telegram/Instagram. Make sure your connection is stable. Long-pressing the link and choosing “Download” also helps.",
  "q3.q": "I cannot sign in with Google",
  "q3.a": "Check your connection and that your browser (Chrome) is up to date. If the app does not reopen after signing in, close it and open it again. If you see “Access blocked”, contact the administrator.",
  "q4.q": "My location is not detected",
  "q4.a": "GPS (Location) must be on and the app must have permission. Try again outdoors. Battery saver mode can reduce accuracy.",
  "q5.q": "My post is not visible to others",
  "q5.a": "An administrator may have blocked it: a red notice appears under the post and only you can see it. Contact the administrator to find out why.",
  "q6.q": "How do I change the language or dark mode?",
  "q6.a": "Profile → Settings. Language: o‘zbekcha, русский, English. Theme: System (follows your phone), Light or Dark.",
  "q7.q": "Is there an iPhone app?",
  "q7.a": "Not yet: the app is Android only.",
  "q8.q": "Is the app safe?",
  "q8.a": "The app only asks for camera and location access. Data lives on a protected server; others see only your name and posts, never your email or phone.",
  "foot.home": "Home",
  "foot.right": ""
 }
};
